package com.erplogic.sap.expense.wsdl2java;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by Apache CXF 3.5.3 2023-09-06T11:00:00.315+05:30
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "service", wsdlLocation = "/integrationhome/wsdl/YGCBELCOY_ExpenseReportWS.wsdl", targetNamespace = "http://483888-one-off.sap.com/YGCBELCOY_")
public class ExpenseReportService extends javax.xml.ws.Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://483888-one-off.sap.com/YGCBELCOY_", "service");
    public static final QName BINDING = new QName("http://483888-one-off.sap.com/YGCBELCOY_", "binding");
    public static final QName BINDINGSOAP12 = new QName("http://483888-one-off.sap.com/YGCBELCOY_", "binding_SOAP12");
    static {
        URL url = null;
        try {
            url = new URL(
                "file:///" + System.getProperty("user.dir") + "/integrationhome/wsdl/YGCBELCOY_ExpenseReportWS.wsdl");
        } catch (final MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExpenseReportService.class.getName()).log(java.util.logging.Level.INFO,
                "Can not initialize the default wsdl from {0}", url);
        }
        WSDL_LOCATION = url;
    }

    public ExpenseReportService(final URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExpenseReportService(final URL wsdlLocation, final QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExpenseReportService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return returns YGCBELCOYExpenseReportWS
     */
    @WebEndpoint(name = "binding")
    public YGCBELCOYExpenseReportWS getBinding() {
        return super.getPort(BINDING, YGCBELCOYExpenseReportWS.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *                 on the proxy. Supported features not in the
     *                 <code>features</code> parameter will have their default
     *                 values.
     * @return returns YGCBELCOYExpenseReportWS
     */

    /**
     *
     * @return returns YGCBELCOYExpenseReportWS
     */
    @WebEndpoint(name = "binding_SOAP12")
    public YGCBELCOYExpenseReportWS getBindingSOAP12() {
        return super.getPort(BINDINGSOAP12, YGCBELCOYExpenseReportWS.class);
    }

}
