
package com.erplogic.sap.expense.wsdl2java;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.5.3 2023-09-06T11:00:00.265+05:30
 * Generated source version: 3.5.3
 */

@WebFault(name = "StandardFaultMessage", targetNamespace = "http://sap.com/xi/AP/Common/Global")
public class StandardFaultMessageException extends Exception {

    private static final long serialVersionUID = 1L;
    private com.erplogic.sap.expense.wsdl2java.StandardFaultMessage faultInfo;

    public StandardFaultMessageException() {
        super();
    }

    public StandardFaultMessageException(final String message) {
        super(message);
    }

    public StandardFaultMessageException(final String message, final java.lang.Throwable cause) {
        super(message, cause);
    }

    public StandardFaultMessageException(final String message,
        final com.erplogic.sap.expense.wsdl2java.StandardFaultMessage standardFaultMessage) {
        super(message);
        this.faultInfo = standardFaultMessage;
    }

    public StandardFaultMessageException(final String message,
        final com.erplogic.sap.expense.wsdl2java.StandardFaultMessage standardFaultMessage,
        final java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = standardFaultMessage;
    }

    public com.erplogic.sap.expense.wsdl2java.StandardFaultMessage getFaultInfo() {
        return this.faultInfo;
    }
}
