package com.erplogic.sap.expense.wsdl2java;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3 2023-09-06T11:00:00.303+05:30
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://483888-one-off.sap.com/YGCBELCOY_", name = "YGCBELCOY_ExpenseReportWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface YGCBELCOYExpenseReportWS {

    @WebMethod(operationName = "Update", action = "http://483888-one-off.sap.com/YGCBELCOY_/YGCBELCOY_ExpenseReportWS/UpdateRequest")
    @WebResult(name = "ExpenseReportUpdateConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ExpenseReportUpdateConfirmation_sync")
    ExpenseReportUpdateConfirmationMessageSync update(

        @WebParam(partName = "ExpenseReportUpdateRequest_sync", name = "ExpenseReportUpdateRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global") ExpenseReportUpdateRequestMessageSync expenseReportUpdateRequestSync)
        throws StandardFaultMessageException;

    @WebMethod(operationName = "QueryByElements", action = "http://483888-one-off.sap.com/YGCBELCOY_/YGCBELCOY_ExpenseReportWS/QueryByElementsRequest")
    @WebResult(name = "ExpenseReportQueryByElementsSimpleByConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ExpenseReportQueryByElementsSimpleByConfirmation_sync")
    ExpenseReportQueryByElementsSimpleByConfirmationMessageSync queryByElements(

        @WebParam(partName = "ExpenseReportQueryByElementsSimpleByRequest_sync", name = "ExpenseReportQueryByElementsSimpleByRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global") ExpenseReportQueryByElementsSimpleByRequestMessageSync expenseReportQueryByElementsSimpleByRequestSync)
        throws StandardFaultMessageException;

    @WebMethod(operationName = "Create", action = "http://483888-one-off.sap.com/YGCBELCOY_/YGCBELCOY_ExpenseReportWS/CreateRequest")
    @WebResult(name = "ExpenseReportCreateConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ExpenseReportCreateConfirmation_sync")
    ExpenseReportCreateConfirmationMessageSync create(

        @WebParam(partName = "ExpenseReportCreateRequest_sync", name = "ExpenseReportCreateRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global") ExpenseReportCreateRequestMessageSync expenseReportCreateRequestSync)
        throws StandardFaultMessageException;

    @WebMethod(operationName = "Read", action = "http://483888-one-off.sap.com/YGCBELCOY_/YGCBELCOY_ExpenseReportWS/ReadRequest")
    @WebResult(name = "ExpenseReportReadByIDResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ExpenseReportReadByIDResponse_sync")
    ExpenseReportReadByIDResponseMessageSync read(

        @WebParam(partName = "ExpenseReportReadByIDQuery_sync", name = "ExpenseReportReadByIDQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global") ExpenseReportReadByIDQueryMessageSync expenseReportReadByIDQuerySync)
        throws StandardFaultMessageException;
}
