server.port: 7000

spring:
  datasource:
    url: jdbc:mysql://demsdev.cnbnff8jyjgm.us-east-1.rds.amazonaws.com:3306/dems?useSSL=true
    username: admin
    password: Erplogic2023
    hikari:
      maximum-pool-size: 50
    
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: none
